import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        secondary: "#c7c6c6",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed-dim": "#c7c6c6",
        "on-surface": "#e5e2e1",
        surface: "#131313",
        "on-tertiary-container": "#636565",
        "inverse-surface": "#e5e2e1",
        "on-primary-fixed-variant": "#454747",
        "surface-container-low": "#1c1b1b",
        "inverse-primary": "#5d5f5f",
        "on-secondary-container": "#b5b5b5",
        "tertiary-container": "#e2e2e2",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-bright": "#393939",
        "on-tertiary-fixed-variant": "#454747",
        "primary-fixed": "#e2e2e2",
        "on-primary-fixed": "#1a1c1c",
        "error-container": "#93000a",
        "surface-dim": "#131313",
        "surface-container-highest": "#353534",
        "on-primary-container": "#636565",
        "tertiary-fixed": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#c6c6c7",
        tertiary: "#ffffff",
        "surface-container": "#201f1f",
        "on-secondary-fixed": "#1b1c1c",
        "on-surface-variant": "#c4c7c8",
        "on-secondary-fixed-variant": "#464747",
        "on-secondary": "#303031",
        "surface-tint": "#c6c6c7",
        "secondary-container": "#464747",
        "secondary-fixed": "#e3e2e2",
        "primary-fixed-dim": "#c6c6c7",
        "primary-container": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "on-primary": "#2f3131",
        error: "#ffb4ab",
        "surface-variant": "#353534",
        outline: "#8e9192",
        "on-background": "#e5e2e1",
        primary: {
          DEFAULT: "var(--primary, #ffffff)",
          foreground: "var(--primary-foreground)",
        },
        "outline-variant": "#444748",
        "inverse-on-surface": "#313030",
        "on-tertiary": "#2f3131",
        "status-green": "#4ade80",
        "status-blue": "#60a5fa",
        "status-yellow": "#fbbf24",
        "status-gray": "#9ca3af",
        "status-available": "#4ade80",
        "status-trip": "#60a5fa",
        "status-offduty": "#9ca3af",
        "status-suspended": "#f87171",
        "status-warning": "#fbbf24",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
      },
      borderRadius: {
        lg: "0.25rem",
        md: "0.25rem",
        sm: "0.125rem",
        xl: "0.5rem",
        full: "0.75rem",
        DEFAULT: "0.125rem"
      },
      spacing: {
        margin: "24px",
        gutter: "16px",
        sidebar_width: "64px",
        sidebar_width_expanded: "240px",
        header_height: "56px",
        container_gap: "12px",
      },
      fontFamily: {
        sans: ["var(--font-inter)"],
        heading: ["var(--font-inter)"],
        "label-sm": ["var(--font-inter)"],
        "headline-md": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "mono-data": ["var(--font-jetbrains-mono)"],
        "label-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "headline-lg": ["var(--font-inter)"],
        "body-sm": ["var(--font-inter)"],
        "headline-sm": ["var(--font-inter)"],
      },
      fontSize: {
        "label-sm": ["10px", { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "mono-data": ["13px", { lineHeight: "1.4", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "500" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "pulse-slow": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-slow": "pulse-slow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;